# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'azdevops-spn'
    azureContainerRegistry: '{"loginServer":"acreshop.azurecr.io", "id" : "/subscriptions/2f6a75ae-9e86-49d6-8782-56786af2bfe0/resourceGroups/rg-eshop-demo/providers/Microsoft.ContainerRegistry/registries/acreshop"}'
    dockerComposeFile: 'eshopmodernizing/eshopmodernizedmvcsolution/src/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'docker-compose -f docker-compose.yml -f docker-compose.override.yml build'
