# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest


steps:
- task: CmdLine@2
  inputs:
    script: |
      nuget restore eShopModernizedMVCSolution\eShopModernizedMVC.sln
- task: VSBuild@1
  inputs:
          solution: 'eShopModernizedMVCSolution\eShopModernizedMVC.sln'
          vsVersion: '16.0'
          msbuildArgs: '/nologo /p:PublishProfile=FolderProfile.pubxml /p:DeployOnBuild=true /p:docker_publish_root=..\..\..\deploy\mvc\'
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'
