apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-db
  labels:
    app: sql-db
spec:
  replicas: 1
  template:
    metadata:
      name: sql-db
      labels:
        app: sql-db
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: sql-db
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: Pass@word2021!
        resources:
          limits:
            cpu: 1
            memory: 3000M
          requests:
            cpu: 1
            memory: 300M
        ports:
          - containerPort: 1433
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-data
  selector:
    matchLabels:
      app: sql-db
---
apiVersion: v1
kind: Service
metadata:
  name: sql-db
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 1433
  selector:
    app: sql-db