version: '3.4'

services:
  eshop.modernized.mvc:
    image: eshop/modernizedmvc:4.8
    platform: windows/amd64
    build:
      context: .\deploy\mvc
      dockerfile: Dockerfile
    depends_on:
     - sql.data

  sql.data:
   image: microsoft/mssql-server-windows-developer