apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-modernized-mvc
  labels:
    app: eshop-modernized-mvc
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      name: eshop-modernized-mvc
      labels:
        app: eshop-modernized-mvc
    spec:
      containers:
      - name: modernizedmvc
        image: acreshop.azurecr.io/eshop/modernizedmvc:4.8
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1
            memory: 800M
          requests:
            cpu: 1
            memory: 300M        
        imagePullPolicy: Always
        env:
        - name: ConnectionString
          value: "Server=sql-data;Database=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=sa;Password=Pass@word2021!"
        - name: UseMockData
          value: "False"
        - name: UseCustomizationData
          value: "False"
        - name: UseAzureStorage
          value: "False"
        - name: StorageConnectionString
          value: ""
        - name: AppInsightsInstrumentationKey
          value: ""
        - name: UseAzureActiveDirectory
          value: "False"
        - name: AzureActiveDirectoryClientId
          value: ""
        - name: AzureActiveDirectoryTenant
          value: ""
        - name: PostLogoutRedirectUri
          value: ""
      nodeSelector:
       "kubernetes.io/os": windows

  selector:
      matchLabels:
        app: eshop-modernized-mvc
  
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-modernized-mvc
spec:
  type: LoadBalancer
  ports:
  - port: 5115
    targetPort: 80
  selector:
    app: eshop-modernized-mvc